server:
  port: 3333

spring:
  application:
    name: check-book-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-add-partitions: true
      bindings:
        input:
          destination: book-topic
          group: books
          binder: kafka
        output:
          destination: check-topic
          group: books
          binder: kafka