server:
  port: 8082

spring:
  application:
    name: check-book-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        output:
          destination: book-topic
  kafka:
    admin:
      properties:
        replication.factor: 1
        partitions: 3